import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';

export async function POST(request: Request) {
  try {
    const supabase = createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    const { query, filters } = body;

    if (!query || typeof query !== 'string') {
      return NextResponse.json({ error: 'Query is required' }, { status: 400 });
    }

    // Mock response - in production this would call the AI service
    const mockAnswer = {
      id: crypto.randomUUID(),
      query,
      answer: `Based on our organizational knowledge, here is what I found regarding "${query}":

This is a synthesized answer that would be generated by the AI service. It would combine information from multiple sources, provide confidence scores, and include proper citations.

The answer would be structured with clear sections, bullet points where appropriate, and inline citations referencing the source materials.`,
      confidence: 0.89,
      sources: [
        {
          id: crypto.randomUUID(),
          connector_type: 'notion',
          title: 'Internal Documentation',
          url: 'https://notion.so/example',
          snippet: 'Relevant excerpt from the source...',
          confidence: 0.92,
        },
        {
          id: crypto.randomUUID(),
          connector_type: 'slack',
          title: '#general - Discussion thread',
          url: 'https://slack.com/example',
          snippet: 'Another relevant excerpt...',
          confidence: 0.85,
        },
      ],
      suggestions: [
        'Can you tell me more about this topic?',
        'What are the exceptions to this?',
        'When was this last updated?',
      ],
      created_at: new Date().toISOString(),
    };

    return NextResponse.json(mockAnswer);
  } catch (error) {
    console.error('Query error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
